/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iuristecnia.ui;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class Login extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * sas
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBg = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jlLogoCiudad = new javax.swing.JLabel();
        jlCiudad = new javax.swing.JLabel();
        jpHeader = new javax.swing.JPanel();
        jpCerrar = new javax.swing.JPanel();
        jlClose = new javax.swing.JLabel();
        jlLogoIuris = new javax.swing.JLabel();
        jlIniciaSesion = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jsUsuario = new javax.swing.JSeparator();
        jlContrasena = new javax.swing.JLabel();
        jsContrasena = new javax.swing.JSeparator();
        jpContrasena = new javax.swing.JPasswordField();
        jpBotonLogin = new javax.swing.JPanel();
        jlBoton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBg.setBackground(new java.awt.Color(255, 255, 255));
        jpBg.setForeground(new java.awt.Color(204, 204, 204));
        jpBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNombre.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(255, 255, 255));
        jlNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNombre.setText("IURISTECNIA");
        jpBg.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 250, -1));

        jlLogoCiudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogoCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iuristecnia/images/logo.png"))); // NOI18N
        jpBg.add(jlLogoCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 250, -1));

        jlCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iuristecnia/images/city.png"))); // NOI18N
        jlCiudad.setText("jLabel1");
        jpBg.add(jlCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 250, 500));

        jpHeader.setBackground(new java.awt.Color(255, 255, 255));
        jpHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpHeaderMouseDragged(evt);
            }
        });
        jpHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpHeaderMousePressed(evt);
            }
        });

        jpCerrar.setBackground(new java.awt.Color(255, 255, 255));

        jlClose.setBackground(new java.awt.Color(255, 255, 255));
        jlClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlClose.setText("X");
        jlClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpCerrarLayout = new javax.swing.GroupLayout(jpCerrar);
        jpCerrar.setLayout(jpCerrarLayout);
        jpCerrarLayout.setHorizontalGroup(
            jpCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCerrarLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jlClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpCerrarLayout.setVerticalGroup(
            jpCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCerrarLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jlClose))
        );

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(758, Short.MAX_VALUE))
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpBg.add(jpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jlLogoIuris.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jlLogoIuris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iuristecnia/images/logoIuris.png"))); // NOI18N
        jlLogoIuris.setText("IURISTECNIA");
        jpBg.add(jlLogoIuris, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jlIniciaSesion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jlIniciaSesion.setText("INICIAR SESIÓN");
        jpBg.add(jlIniciaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jlUsuario.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        jlUsuario.setText("USUARIO");
        jpBg.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, -1));

        jtUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jtUsuario.setText("Introduzca nombre de usuario");
        jtUsuario.setBorder(null);
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtUsuarioMousePressed(evt);
            }
        });
        jpBg.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 430, 30));

        jsUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jpBg.add(jsUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 233, 430, 10));

        jlContrasena.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        jlContrasena.setText("CONTRASEÑA");
        jpBg.add(jlContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, -1));

        jsContrasena.setForeground(new java.awt.Color(0, 0, 0));
        jpBg.add(jsContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 430, 10));

        jpContrasena.setForeground(new java.awt.Color(204, 204, 204));
        jpContrasena.setText("********");
        jpContrasena.setBorder(null);
        jpContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpContrasenaMousePressed(evt);
            }
        });
        jpBg.add(jpContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 430, 30));

        jpBotonLogin.setBackground(new java.awt.Color(0, 134, 190));

        jlBoton.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jlBoton.setForeground(new java.awt.Color(255, 255, 255));
        jlBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBoton.setText("ENTRAR");
        jlBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpBotonLoginLayout = new javax.swing.GroupLayout(jpBotonLogin);
        jpBotonLogin.setLayout(jpBotonLoginLayout);
        jpBotonLoginLayout.setHorizontalGroup(
            jpBotonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpBotonLoginLayout.setVerticalGroup(
            jpBotonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpBg.add(jpBotonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 150, 40));

        getContentPane().add(jpBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jpHeaderMousePressed

    private void jpHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpHeaderMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
        
    }//GEN-LAST:event_jpHeaderMouseDragged

    private void jlCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlCloseMouseClicked

    private void jlCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCloseMouseExited
        jpCerrar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jlCloseMouseExited

    private void jlCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCloseMouseEntered
        jpCerrar.setBackground(Color.red);
    }//GEN-LAST:event_jlCloseMouseEntered

    private void jlBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotonMouseEntered
        jpBotonLogin.setBackground(new Color(0,156,223));
    }//GEN-LAST:event_jlBotonMouseEntered

    private void jlBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotonMouseExited
        jpBotonLogin.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_jlBotonMouseExited

    private void jtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMousePressed
        if (jtUsuario.getText().equals("Introduzca nombre de usuario")) {
            jtUsuario.setText("");
            jtUsuario.setForeground(Color.black);
        }
        if (String.valueOf(jpContrasena.getPassword()).isEmpty()) {
            jpContrasena.setText("********");
            jpContrasena.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtUsuarioMousePressed

    private void jpContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpContrasenaMousePressed
        if(String.valueOf(jpContrasena.getPassword()).equals("********")) {
            jpContrasena.setText("");
            jpContrasena.setForeground(Color.black);       

        }
        
        if (String.valueOf(jtUsuario.getText()).isEmpty()) {
            jtUsuario.setText("Introduzca nombre de usuario");
            jtUsuario.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_jpContrasenaMousePressed

    private void jlBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotonMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Intento de acceso con la contraseña "+ String.valueOf(jpContrasena.getPassword())+"\n", "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jlBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlBoton;
    private javax.swing.JLabel jlCiudad;
    private javax.swing.JLabel jlClose;
    private javax.swing.JLabel jlContrasena;
    private javax.swing.JLabel jlIniciaSesion;
    private javax.swing.JLabel jlLogoCiudad;
    private javax.swing.JLabel jlLogoIuris;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel jpBg;
    private javax.swing.JPanel jpBotonLogin;
    private javax.swing.JPanel jpCerrar;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JSeparator jsContrasena;
    private javax.swing.JSeparator jsUsuario;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
